### ISSUE TITLE
Highlight keywords without colon

### ISSUE THREAD

**Issue by lackovic** [wayou/vscode-todo-highlight#105]
I honestly haven't seen anyone using the colon after TODO and I find it quite unnecessary.

Is there a way I can have the plugin work on all the keywords, without the colon, without having to reconfigure them completely in the user settings?

**Comment by maxgardner** [comment]
Yep, see issue #93 for a quick workaround with your VSCode settings.

**Comment by wayou** [comment]
solved in the newest v1 release, just check it out.

**Comment by maxgardner** [comment]
I upgraded to the latest v1, but it doesn't seem like this issue is resolved. It still has the unnecessary level of specificity that you have to include a colon to have it recognize the keyword. It doesn't make sense that this would be default because not including the colon fits broader use cases while still covering the case for people who do use a colon.

[![example of keywords that don't work](https://s33.postimg.cc/z27o59tsv/Screen_Shot_2018-07-23_at_8.37.13_AM.png)](https://postimg.cc/image/wkvwy09wb/)

Am I possibly missing something here? Is there a certain setting we use to change this? Currently, I've copied the exact default settings to my user settings, just without the colon. That's rather frustrating, though.

**Comment by homer-jay** [comment]
Just use this setting:
```"todohighlight.keywordsPattern": "\\b(TODO|FIXME)\\b"```

That said, this extension should add an option for semicolons without forcing people into regexes.
