### ISSUE TITLE
[feature request] regex pattern in keywords

### ISSUE THREAD

**Issue by theGiallo** [wayou/vscode-todo-highlight#88]
I would really powerful to have regex not only in a single string but on every keyword. E.g. I use `NOTE(username): stuff` or `TODO(username,date): stuff`.

**Comment by wayou** [comment]
multiple regex make the extension  much more complex, witch I think it's already been complex than the original purpose when I made this extension :(.
however, you request can do be met with the working one option `todohighlight.keywordsPattern`.

**Comment by theGiallo** [comment]
If I'm not mistaken that option gets me a single color. I'd like many colors.

A problem I have with the keywords is that they are not matched as "whole word". E.g. "NOTE" is matched in "NOTEPAD".

**Comment by adamreisnz** [comment]
@wayou Is this still supported, or has it since been removed? I can't seem to make it work using the examples in that commit. Using "pattern" doesn't seem to work. I need to be able to specify a boundary for individual keywords. Using a single keywordsPattern is not suitable.

![image](https://user-images.githubusercontent.com/490562/107142921-ea30a700-6996-11eb-9349-61a65a0f418f.png)

This doesn't work.

**Comment by wayou** [comment]
> @wayou Is this still supported, or has it since been removed? I can't seem to make it work using the examples in that commit. Using "pattern" doesn't seem to work. I need to be able to specify a boundary for individual keywords. Using a single keywordsPattern is not suitable.

I'm afraid the `\b` won't work, see https://github.com/wayou/vscode-todo-highlight/pull/50#issuecomment-316257578
